create table `controle-estorno` (codigo_produto integer not null, date_atualizacao_estorno datetime(6), date_estorno datetime(6), id bigint not null auto_increment, saldo_anterior bigint, saldo_atualizado bigint, descricao_estorno varchar(255), descricao_produto varchar(255), nome_responsável varchar(255), primary key (id)) engine=InnoDB;
create table `controle-estorno` (codigo_produto integer not null, date_atualizacao_estorno datetime(6), date_estorno datetime(6), id bigint not null auto_increment, saldo_anterior bigint, saldo_atualizado bigint, descricao_estorno varchar(255), descricao_produto varchar(255), nome_responsável varchar(255), primary key (id)) engine=InnoDB;

    create table "controle-estorno" (
        codigo_produto integer not null,
        date_atualizacao_estorno timestamp(6),
        date_estorno timestamp(6),
        id bigint generated by default as identity,
        saldo_anterior bigint,
        saldo_atualizado bigint,
        descricao_estorno varchar(255),
        descricao_produto varchar(255),
        nome_responsável varchar(255),
        primary key (id)
    );
